name: Test
on: workflow_dispatch
jobs:
  integration-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Backend integration tests
        run: pytest -vs test --html pytest.html
      
      - name: Save test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: pytest.html